from pathlib import Path
from .land import Coord, Zone


def format_input(user_input):
    """Formats the input coordinates into z zone.

    Args:
        user_input (str): input to parse.

    Returns:
        (Zone): The zone generated by the input.
    """
    values = [int(i) for i in user_input.strip().split(" ")]
    start = Coord(values[0], values[1])
    end = Coord(values[2], values[3])
    return Zone(start, end)


def format_raw_input(user_input):
    """Format input for the GUI application.

    Args:
        user_input (str): Raw input from the UI

    Returns:
        list[list[int]]: Each input converted into a list of integers.
    """
    # Replace silly “ or ” characters with "
    # TODO: Swap out with regex
    raw_input = user_input.strip().replace(
        '“', '"').replace("”", '"').replace(",", "").replace("\n", " ")
    # Break apart the string into each coordinate
    raw_inputs = [r.replace('"', '') for r in raw_input.split('" "')]
    # Return coordinates as lists of ints.
    return [[int(i) for i in r.split(" ")] for r in raw_inputs]


def get_icon():
    """Gets the icon file from the resources directory.

    Returns:
        icon (str): The path the the icon file.
    """
    icon = Path(__file__).parent.joinpath("resources", "icon.png")
    # We just want the string to the path for PySide.
    return str(icon)


def get_css():
    """Gets the style.css file from the resources directory.

    Returns:
        css_data (str): The data from the style.css file.
    """
    css = Path(__file__).parent.joinpath("resources", "style.css")

    with open(css, "r") as style_file:
        css_data = style_file.read()

    return css_data
